services:
     gbrfix_user.identifier:
        class: Gbrfix\UserBundle\Service\UserIdentifier
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            
     gbrfix_user.login_listener:
        class: Gbrfix\UserBundle\Service\LoginListener
        arguments:
            - "@gbrfix_user.identifier"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: processIdentification }