<?php

namespace Gbrfix\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository {
	public function getAdverts($page, $nbPerPage) {
		$query = $this->createQueryBuilder('a')
			->leftJoin('a.image', 'i')
			->addSelect('i')
			->leftJoin('a.categories', 'c')
			->addSelect('c')
			->orderBy('a.date', 'desc')
			->getQuery();
		
		$query->setFirstResult(($page-1)*$nbPerPage)
			->setMaxResults($nbPerPage);
		
		return new Paginator($query, true);
	}
	
	public function isFlood($ip, $delay) {
		$date = new \DateTime();
		$date->modify('-'.$delay.' second');
		
		// TODO: Verifier l'ip de User et supprimer le champ ip de Advert
		$query = $this->createQueryBuilder('a')
			->where('a.ip = :ip')
			->setParameter('ip', $ip)
			->andWhere('a.date >= :date')
			->setParameter('date', $date)
			->getQuery();
		
		return !empty($query->getArrayResult());
	}
}
