<?php

namespace Gbrfix\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository {
	public function getApplicationsWithAdvert($limit) {
		$qb = $this->createQueryBuilder('a')
			->innerJoin('a.advert', 'adv')
			->addSelect('adv');
		
		$qb->orderBy('a.date', 'DESC')
			->setMaxResults($limit);
		
		return $qb->getQuery()->getResult();
	}
}
