# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Gbrfix\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: 1234, roles: [ 'ROLE_USER' ] }
                    admin: { password: 123456, roles: [ 'ROLE_ADMIN' ] }
        my:
            entity:
                class: Gbrfix\UserBundle\Entity\User
                property: username
                
        fos:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pare-feu non-securisé uniquement pour le formulaire de connexion
        #main_login:
            #pattern: ^/login$
            #anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: fos
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /%locale%/platform
            logout:
                path: fos_user_security_logout
                target: /%locale%/platform
            remember_me:
                secret: %secret% # voir parameters.yml
                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
